// Generated by scripts/gen-messages-types.ts from messages/*.json. Do not
// edit: run `pnpm --filter @oxagen/app gen:messages`; CI fails when this
// file is stale (INV-12).
type Messages = {
  app: {
    name: string;
    description: string;
  };
  pages: {
    login: string;
    signup: string;
    verify: string;
    twoFactor: string;
    forgotPassword: string;
    resetPassword: string;
    invitation: string;
    invitationNotFound: string;
    newOrganization: string;
    register: string;
    cliAuthorize: string;
    cliComplete: string;
    fleet: string;
    run: string;
    agents: string;
    agent: string;
    agentSource: string;
    mandate: string;
    tools: string;
    skills: string;
    steering: string;
    spend: string;
    people: string;
    roles: string;
    apiKeys: string;
    billing: string;
    audit: string;
    modelFunding: string;
  };
  unrecorded: {
    run: {
      frames_wrapped: string;
    };
  };
  notFound: {
    title: string;
    body: string;
    home: string;
  };
  globalError: {
    title: string;
    body: string;
    retry: string;
  };
  agents: {
    notRecorded: string;
    harness: {
      stella: string;
      "claude-code": string;
      codex: string;
      cursor: string;
      "claude-agent-sdk": string;
      custom: string;
    };
    status: {
      unenrolled: string;
      enrolled: string;
      suspended: string;
      retired: string;
    };
    list: {
      tiles: {
        label: string;
        identities: {
          title: string;
          basis: string;
        };
        enrolled: {
          title: string;
          basis: string;
        };
        tamper: {
          title: string;
          basis: string;
        };
      };
      title: string;
      tableLabel: string;
      columns: {
        identity: string;
        harness: string;
        operator: string;
        status: string;
        runs: string;
        spend: string;
        incidents: string;
        actions: string;
      };
      basisNotRecorded: string;
      edit: string;
      pager: string;
      first: string;
      next: string;
      empty: {
        title: string;
        body: string;
        register: string;
        command: string;
      };
    };
    detail: {
      header: string;
      seeBelt: string;
      tabs: {
        label: string;
        identity: string;
        toolbelt: string;
        enrollment: string;
        incidents: string;
        definition: string;
        mandates: string;
      };
      identity: {
        title: string;
        lead: string;
        agentKey: string;
        principal: string;
        harness: string;
        operator: string;
        status: string;
        registered: string;
        firstFrame: string;
        noFrame: string;
      };
      roles: {
        title: string;
        lead: string;
        empty: string;
        columns: {
          role: string;
          scope: string;
          assigned: string;
          expires: string;
        };
        scope: {
          org: string;
          workspace: string;
        };
        standing: string;
      };
      credentials: {
        title: string;
        lead: string;
        empty: string;
        columns: {
          key: string;
          issued: string;
          lastUsed: string;
          expires: string;
          state: string;
        };
        never: string;
        noExpiry: string;
        active: string;
        expired: string;
        revoked: string;
      };
      toolbelt: {
        title: string;
        computation: {
          title: string;
          computedAt: string;
          ceiling: string;
          ceilingValue: {
            caller: string;
            sentinel: string;
          };
          roleGrants: string;
          denyGeneration: string;
          denyGenerationValue: string;
          killSwitches: string;
        };
        presentation: {
          title: string;
          mode: {
            full: string;
            searchable: string;
          };
          sent: {
            definitions: string;
            meta_tools: string;
          };
          limit: string;
        };
        tools: {
          title: string;
          empty: string;
          columns: {
            tool: string;
            category: string;
            risk: string;
            decision: string;
            rule: string;
            access: string;
          };
          risk: {
            low: string;
            medium: string;
            high: string;
          };
          decision: {
            allow: string;
            require_approval: string;
          };
          readOnly: string;
          writes: string;
        };
        cannotSee: {
          title: string;
          empty: string;
          columns: {
            tool: string;
            rule: string;
          };
        };
      };
      enrollment: {
        title: string;
        lead: string;
        columns: {
          host: string;
          status: string;
          mode: string;
          collector: string;
          hooks: string;
          bundle: string;
          deviceKey: string;
          lastSeen: string;
        };
        hooks: {
          ok: string;
          missing: string;
          unreported: string;
        };
        bundleVersion: string;
        never: string;
        revoked: string;
        expired: string;
        empty: {
          title: string;
          body: string;
          command: string;
        };
      };
      incidents: {
        title: string;
        empty: string;
        columns: {
          kind: string;
          severity: string;
          detected: string;
          session: string;
          state: string;
        };
        severity: {
          notice: string;
          warning: string;
          tamper: string;
        };
        detectedBy: {
          collector: string;
          control_plane: string;
          human: string;
        };
        open: string;
        resolved: string;
        pager: string;
        first: string;
        next: string;
      };
      definition: {
        openEditor: string;
        none: {
          title: string;
          body: string;
        };
        unparsed: string;
        fields: {
          title: string;
          schema: string;
          slug: string;
          name: string;
          description: string;
          modelTier: string;
          budget: string;
          tools: string;
          denyTools: string;
          sideEffects: string;
          harness: string;
          instructions: string;
          unset: string;
        };
        source: {
          title: string;
          lead: string;
          path: string;
          branch: string;
          commit: string;
          digest: string;
          pullRequest: string;
          committed: string;
        };
      };
    };
    actions: {
      rotate: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        done: string;
        expires: string;
      };
      suspend: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      resume: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      retire: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        delegationCeiling: string;
        agentNotFound: string;
        agentRetired: string;
        agentPrincipalMissing: string;
        noRepository: string;
        repositoryAmbiguous: string;
        branchIsDefault: string;
        definitionSchema: string;
        definitionSlug: string;
        timeZoneUnavailable: string;
        timeZoneUnsupported: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
        noToolMatches: string;
        measureNotDeclared: string;
        measureUnitMismatch: string;
      };
    };
    source: {
      facts: string;
      loading: string;
      branchAt: string;
      uncommitted: string;
      truth: string;
      lead: string;
      back: string;
      discard: string;
      save: string;
      modified: string;
      unchanged: string;
      stat: string;
      parse: {
        error: string;
        reason: {
          unterminated_string: string;
          unterminated_array: string;
          array_separator: string;
          inline_table_key: string;
          inline_table_separator: string;
          missing_value: string;
          unreadable_value: string;
          expected_key_value: string;
          text_after_value: string;
        };
      };
      commit: {
        title: string;
        diff: string;
        branch: string;
        branchHint: string;
        message: string;
        messageHint: string;
        submit: string;
        pending: string;
        done: string;
        pullRequest: string;
        invalid: {
          branch: string;
          message: string;
          source: string;
        };
      };
    };
    mandates: {
      title: string;
      noneTitle: string;
      lead: string;
      none: string;
      noneDetail: string;
      authority: string;
      columns: {
        mandate: string;
        effect: string;
        tools: string;
        perCall: string;
        perPeriod: string;
        remaining: string;
        validTo: string;
        status: string;
      };
      status: {
        draft: string;
        active: string;
        expired: string;
        revoked: string;
      };
      request: {
        open: string;
        title: string;
        body: string;
        measure: string;
        measureHint: string;
        perCall: string;
        perPeriod: string;
        perPeriodHint: string;
        period: string;
        periods: {
          daily: string;
          weekly: string;
          monthly: string;
        };
        callsPerDay: string;
        tools: string;
        toolsHint: string;
        purpose: string;
        purposeHint: string;
        validFrom: string;
        validTo: string;
        validToHint: string;
        confirm: string;
        pending: string;
        unit: string;
        unitHint: string;
        perCallHint: string;
        consequenceTags: string;
        consequenceTagsHint: string;
        consequenceOther: string;
      };
      truncated: string;
      noneEffective: string;
      noneListedTitle: string;
      partial: string;
      noneListed: string;
      noneListedDetail: string;
      retired: string;
      noneEffectiveUpcoming: string;
      startsOn: string;
    };
  };
  audit: {
    eyebrow: string;
    description: string;
    loading: string;
    events: {
      title: string;
      when: string;
      event: string;
      actor: string;
      what: string;
      result: string;
      more: string;
      workspace: string;
      ip: string;
      request: string;
      userAgent: string;
      notRecorded: string;
    };
    outcomes: {
      allow: string;
      deny: string;
      error: string;
      success: string;
    };
    filters: {
      label: string;
      eventType: string;
      anyEventType: string;
      outcome: string;
      anyOutcome: string;
      actor: string;
      anyActor: string;
      capability: string;
      from: string;
      to: string;
      apply: string;
      clear: string;
    };
    export: {
      csv: string;
      ndjson: string;
    };
    pager: {
      label: string;
      newer: string;
      older: string;
      end: string;
    };
    empty: {
      title: string;
      body: string;
      action: string;
    };
    filteredEmpty: {
      title: string;
      body: string;
    };
    error: {
      title: string;
      body: string;
      code: string;
      retry: string;
    };
    denied: {
      title: string;
      body: string;
    };
    pending: {
      title: string;
      body: string;
    };
    roles: {
      owner: string;
      admin: string;
      member: string;
      billing: string;
      compliance: string;
      viewer: string;
    };
  };
  auth: {
    shell: {
      brand: string;
      tags: {
        free: string;
        markup: string;
        evidence: string;
      };
    };
    fields: {
      name: string;
      email: string;
      password: string;
      newPassword: string;
      confirmPassword: string;
      code: string;
      backupCode: string;
      rememberMe: string;
      showPassword: string;
      hidePassword: string;
      passwordHint: string;
    };
    errors: {
      emailRequired: string;
      emailInvalid: string;
      passwordRequired: string;
      passwordTooShort: string;
      passwordTooLong: string;
      passwordsDiffer: string;
      nameRequired: string;
      nameTooLong: string;
      codeInvalid: string;
      backupCodeInvalid: string;
      tokenMissing: string;
    };
    outcomes: {
      wrongCredentials: string;
      emailNotVerified: string;
      suspended: string;
      rateLimited: string;
      alreadyRegistered: string;
      codeWrong: string;
      linkExpired: string;
      oauthCancelled: string;
      oauthFailed: string;
      unavailable: string;
      unknown: string;
    };
    sso: {
      google: string;
      github: string;
      or: string;
    };
    login: {
      eyebrow: string;
      title: string;
      lead: string;
      forgot: string;
      submit: string;
      pending: string;
      newHere: string;
      createAccount: string;
      haveInvite: string;
    };
    signup: {
      eyebrow: string;
      lead: string;
      submit: string;
      pending: string;
      terms: string;
      haveAccount: string;
      logIn: string;
    };
    verify: {
      eyebrow: string;
      lead: string;
      leadNoEmail: string;
      expired: string;
      resendTitle: string;
      resend: string;
      resendPending: string;
      resent: string;
      wrongAddress: string;
      startOver: string;
    };
    twoFactor: {
      eyebrow: string;
      title: string;
      lead: string;
      leadBackup: string;
      submit: string;
      pending: string;
      useBackup: string;
      useTotp: string;
      back: string;
    };
    forgot: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      sentTitle: string;
      sentBody: string;
      again: string;
      back: string;
    };
    reset: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      doneTitle: string;
      doneBody: string;
      logIn: string;
      expiredTitle: string;
      expiredBody: string;
      requestNew: string;
      back: string;
    };
    invite: {
      eyebrow: string;
      invited: string;
      invitedOn: string;
      organization: string;
      role: string;
      sentTo: string;
      expires: string;
      never: string;
      roles: {
        owner: string;
        admin: string;
        member: string;
        billing: string;
        compliance: string;
        viewer: string;
      };
      accept: string;
      accepting: string;
      decline: string;
      declining: string;
      declined: string;
      signInLead: string;
      logIn: string;
      signUp: string;
      signedInAs: string;
      notYou: string;
      wrongAccountTitle: string;
      wrongAccountBody: string;
      logInAsOther: string;
      notFoundTitle: string;
      notFoundBody: string;
      closed: {
        accepted: string;
        declined: string;
        revoked: string;
        expired: string;
      };
      closedTitle: string;
      failed: string;
      denied: string;
    };
    cli: {
      title: string;
      lead: string;
      organization: string;
      workspace: string;
      grantsTitle: string;
      grantKeys: string;
      grantActs: string;
      approve: string;
      approving: string;
      cancel: string;
      cancelling: string;
      invalidTitle: string;
      invalidBody: string;
      invalid: {
        redirectUri: string;
        codeChallenge: string;
        codeChallengeMethod: string;
        state: string;
      };
      errors: {
        notPermitted: string;
        notFound: string;
        failed: string;
      };
      complete: {
        title: string;
        body: string;
      };
    };
  };
  billing: {
    units: {
      gau: string;
    };
    range: string;
    notRecorded: string;
    header: {
      eyebrow: string;
      description: string;
    };
    checkout: {
      success: string;
      cancel: string;
      credits: string;
      plan: string;
    };
    tiers: {
      free: string;
      build: string;
      scale: string;
      enterprise: string;
    };
    intervals: {
      month: string;
      year: string;
    };
    tiles: {
      label: string;
      plan: string;
      planMonth: string;
      planYear: string;
      planNone: string;
      gau: string;
      gauNote: string;
      overdrawn: string;
      rate: string;
      perThousand: string;
      due: string;
      dueNote: string;
      nothingDue: string;
      nextInvoice: string;
      mixedCurrency: string;
    };
    thisMonth: {
      title: string;
      columns: {
        line: string;
        basis: string;
        amount: string;
      };
      lines: {
        plan: string;
        blocks: string;
        topups: string;
        overage: string;
        tax: string;
        total: string;
      };
      basis: {
        plan: string;
        planNone: string;
        invoices: string;
        tax: string;
        total: string;
      };
      none: string;
      empty: string;
      partial: string;
      mixedCurrency: string;
    };
    meters: {
      title: string;
      columns: {
        meter: string;
        thisMonth: string;
        note: string;
      };
      gau: string;
      gauValue: string;
      gauNote: string;
      remaining: string;
      overdrawn: string;
      other: string;
      otherNote: string;
      held: string;
      heldNote: string;
      credits: string;
      creditsValue: string;
      creditsNote: string;
      exhaustedNoCard: string;
    };
    mode: {
      prepaid: string;
      prepaidNoCard: string;
      invoice: string;
      uninvoiced: string;
      invoiced: string;
      pastDue: string;
    };
    invoices: {
      title: string;
      empty: string;
      columns: {
        invoice: string;
        period: string;
        kind: string;
        amount: string;
        status: string;
        paid: string;
        link: string;
      };
      unnumbered: string;
      view: string;
      unpublished: string;
      kinds: {
        subscription: string;
        gau_purchase: string;
        gau_auto_topup: string;
        gau_interim: string;
        gau_period_close: string;
      };
      statuses: {
        open: string;
        paid: string;
        uncollectible: string;
        void: string;
      };
      pager: string;
      older: string;
      newest: string;
    };
    priceList: {
      title: string;
      governed: string;
      inApp: string;
      free: string;
      freeTerms: string;
      perMonth: string;
      enterprise: string;
      enterpriseTerms: string;
      list: string;
      perThousand: string;
      blocks: string;
      blockTerms: string;
      bands: string;
      credit: string;
      creditTerms: string;
      calls: string;
      callsTerms: string;
      grant: string;
      packs: string;
      packsTerms: string;
      everyFeature: string;
    };
    autoTopup: {
      title: string;
      enabled: string;
      blocks: string;
      perTopup: string;
      readOnly: string;
      save: string;
      saving: string;
      saved: string;
      invalidBlocks: string;
      failed: string;
      savedCard: string;
      savedCardUnlabelled: string;
      noCard: string;
      attempt: {
        none: string;
        paid: string;
        open: string;
        failed: string;
      };
    };
    purchase: {
      title: string;
      quantity: string;
      step: string;
      total: string;
      wholeBlocks: string;
      savesCard: string;
      submit: string;
      submitting: string;
      denied: string;
      errors: {
        invalid: string;
        aboveMax: string;
        denied: string;
        conflict: string;
        unavailable: string;
      };
    };
    usageCredits: {
      title: string;
      balance: string;
      faceValue: string;
      credits: string;
      basis: string;
      exhausted: string;
      presets: string;
      amount: string;
      min: string;
      submit: string;
      submitting: string;
      denied: string;
      planDenied: string;
      errors: {
        invalid: string;
        denied: string;
        unavailable: string;
      };
    };
    whatCounts: {
      title: string;
      gau: string;
      gauBody: string;
      credits: string;
      creditsBody: string;
      free: string;
      freeBody: string;
      reported: string;
      reportedBody: string;
    };
    changePlan: {
      open: string;
      title: string;
      lede: string;
      plan: string;
      interval: string;
      perMonth: string;
      perYear: string;
      includes: string;
      enterprise: string;
      submit: string;
      submitting: string;
      denied: string;
      subscribed: string;
      errors: {
        invalid: string;
        denied: string;
        conflict: string;
        unavailable: string;
      };
    };
    rate: {
      published: string;
      negotiated: string;
      negotiatedNoRef: string;
    };
    failure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
  };
  fleet: {
    stats: {
      label: string;
      live: {
        title: string;
        basis: string;
      };
      waiting: {
        title: string;
        oldest: string;
        none: string;
      };
    };
    approvals: {
      title: string;
      parked: string;
      empty: string;
      emptyDetail: string;
      agent: string;
      requester: string;
      timesOut: string;
      notRecorded: string;
      openRun: string;
      mandateUnread: string;
      mandatePeriodBasis: string;
      mandatePerCallOnly: string;
    };
    runs: {
      title: string;
      columns: {
        run: string;
        agent: string;
        operator: string;
        status: string;
        replay: string;
        cost: string;
        frames: string;
        started: string;
      };
      noSummary: string;
      notRecorded: string;
      basisNotRecorded: string;
      source: {
        ledger: string;
        tacho: string;
      };
      older: string;
      newest: string;
      pager: string;
      empty: {
        title: string;
        body: string;
        enroll: string;
        command: string;
      };
    };
  };
  mandate: {
    eyebrow: string;
    roles: {
      owner: string;
      admin: string;
      member: string;
      billing: string;
      compliance: string;
      viewer: string;
    };
    loading: string;
    grantedBy: string;
    notGranted: string;
    status: {
      draft: string;
      active: string;
      expired: string;
      revoked: string;
    };
    tiles: {
      label: string;
      perCall: string;
      perCallBasis: string;
      perPeriod: string;
      perPeriodBasis: string;
      settled: string;
      settledBasis: string;
      remaining: string;
      remainingBasis: string;
    };
    ledger: {
      title: string;
      label: string;
      basis: string;
      note: string;
      columns: {
        when: string;
        call: string;
        amount: string;
        state: string;
        external: string;
        receipt: string;
      };
      kind: {
        reserve: string;
        settle: string;
        release: string;
      };
      notRecorded: string;
      callBasis: string;
      receiptBasis: string;
      readBound: string;
      empty: string;
      emptyBody: string;
      filteredEmpty: string;
      filteredEmptyBody: string;
      search: string;
      searchHint: string;
      state: string;
      anyState: string;
      apply: string;
      clear: string;
      shown: string;
      pager: {
        label: string;
        newer: string;
        older: string;
        end: string;
      };
      emptyBodyEffective: string;
    };
    grant: {
      title: string;
      agent: string;
      grantedBy: string;
      notGranted: string;
      requestedBy: string;
      roleAtGrant: string;
      effect: string;
      counterparties: string;
      allow: string;
      deny: string;
      anyTarget: string;
      noPattern: string;
      allowAnyTarget: string;
      anyNotDenied: string;
      tools: string;
      approval: string;
      approvalAbove: string;
      approvalAlways: string;
      approvalNone: string;
      approvalApprovers: string;
      approvalConsequenceRoles: string;
      valid: string;
      validWindow: string;
      validWindowBasis: string;
    };
    reconciliation: {
      title: string;
      body: string;
      notRecorded: string;
      openAudit: string;
    };
    actions: {
      limits: {
        open: string;
        title: string;
        body: string;
        measure: string;
        measureHint: string;
        unit: string;
        unitHint: string;
        perCall: string;
        perPeriod: string;
        period: string;
        periods: {
          daily: string;
          weekly: string;
          monthly: string;
        };
        validTo: string;
        validToHint: string;
        confirm: string;
        pending: string;
        callsPer: string;
        periodsPer: {
          daily: string;
          weekly: string;
          monthly: string;
        };
      };
      revoke: {
        open: string;
        title: string;
        body: string;
        reason: string;
        reasonHint: string;
        confirm: string;
        pending: string;
        draft: {
          open: string;
          title: string;
          body: string;
          confirm: string;
          pending: string;
        };
      };
      failure: {
        orgRoleRequired: string;
        noRoleCoversAllTags: string;
        mandateNotFound: string;
        mandateEnded: string;
        validityInverted: string;
        noToolMatches: string;
        measureNotDeclared: string;
        measureUnitMismatch: string;
        periodDrawn: string;
        noPrincipal: string;
        timeZoneUnavailable: string;
        timeZoneUnsupported: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
    failure: {
      back: string;
      denied: {
        title: string;
        body: string;
        signedIn: string;
        needed: string;
        decidedBy: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
        readAt: string;
        retry: string;
      };
    };
  };
  onboarding: {
    errors: {
      orgNameRequired: string;
      orgNameTooLong: string;
      slugInvalid: string;
      slugReserved: string;
      workspaceNameRequired: string;
      workspaceNameTooLong: string;
      workspaceSlugInvalid: string;
      workspaceSlugReserved: string;
      slugTaken: string;
      agentSlugInvalid: string;
      agentNameRequired: string;
      agentNameTooLong: string;
      agentDescriptionTooLong: string;
      agentHarnessInvalid: string;
      failed: string;
      denied: string;
    };
    organization: {
      eyebrow: string;
      title: string;
      lead: string;
      name: string;
      slug: string;
      slugHint: string;
      workspaceTitle: string;
      workspaceName: string;
      workspaceSlug: string;
      workspaceHint: string;
      creates: string;
      submit: string;
      pending: string;
    };
    gate: {
      title: string;
      lead: string;
      railLabel: string;
      steps: {
        organization: string;
        wrap: string;
        run: string;
      };
      subs: {
        organization: string;
        wrap: string;
        run: string;
      };
      state: {
        done: string;
        current: string;
        todo: string;
      };
      provisional: {
        badge: string;
        title: string;
        body: string;
        detected: string;
        binding: string;
        noRepository: string;
      };
      firstRun: {
        badge: string;
        title: string;
        body: string;
        open: string;
      };
    };
    register: {
      eyebrow: string;
      railLabel: string;
      steps: {
        name: string;
        wrap: string;
        run: string;
      };
      state: {
        done: string;
        current: string;
        todo: string;
      };
      caption: string;
      noAgent: {
        title: string;
        body: string;
        start: string;
      };
      name: {
        title: string;
        lead: string;
        slug: string;
        slugHint: string;
        agentName: string;
        agentNameHint: string;
        harness: string;
        harnessHint: string;
        description: string;
        descriptionHint: string;
        note: string;
        submit: string;
        pending: string;
        registered: {
          title: string;
          body: string;
          expires: string;
          continue: string;
        };
      };
      wrap: {
        title: string;
        lead: string;
        agentKey: string;
        harness: string;
        notRecorded: string;
        host: {
          title: string;
          body: string;
          mint: string;
          pending: string;
          again: string;
        };
        sdk: {
          title: string;
          body: string;
          install: string;
          credential: string;
        };
        token: {
          label: string;
          once: string;
          expires: string;
          command: string;
        };
        back: string;
        continue: string;
        advancing: string;
      };
      run: {
        title: string;
        lead: string;
        waiting: {
          title: string;
          body: string;
          again: string;
          checking: string;
        };
        host: {
          enrolled: string;
          none: string;
          heartbeat: string;
          noHeartbeat: string;
          hooksOk: string;
          hooksMissing: string;
          hooksUnreported: string;
        };
        received: {
          title: string;
          body: string;
          at: string;
          open: string;
        };
        repository: {
          title: string;
          body: string;
          bind: string;
          binding: string;
          skip: string;
        };
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        agentNotFound: string;
        slugTaken: string;
        gateNotFound: string;
        alreadyUnlocked: string;
        firstFrameRequired: string;
        githubNotConnected: string;
        repositoryNotInstalled: string;
        mainRepoBound: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
  };
  organization: {
    tabs: {
      label: string;
      people: string;
      roles: string;
      apiKeys: string;
      modelFunding: string;
    };
    roles: {
      owner: string;
      admin: string;
      member: string;
      billing: string;
      compliance: string;
      viewer: string;
    };
    people: {
      title: string;
      person: string;
      role: string;
      joined: string;
      actions: string;
      empty: string;
    };
    actions: {
      readOnly: string;
      denied: string;
      fields: {
        name: string;
        description: string;
        scope: string;
        slug: string;
        slugHint: string;
        mainRepo: string;
        mainRepoHint: string;
        permissions: string;
        roleNameHint: string;
      };
      createRole: {
        open: string;
        title: string;
        confirm: string;
        pending: string;
      };
      editRole: {
        open: string;
        title: string;
        confirm: string;
        pending: string;
      };
      deleteRole: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      createWorkspace: {
        open: string;
        title: string;
        confirm: string;
        pending: string;
      };
      editWorkspace: {
        open: string;
        title: string;
        confirm: string;
        pending: string;
      };
      archiveWorkspace: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      role: {
        open: string;
        title: string;
        body: string;
        label: string;
        confirm: string;
        pending: string;
      };
      remove: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        delegationCeiling: string;
        roleExists: string;
        roleNotFound: string;
        roleInUse: string;
        systemRoleReadonly: string;
        slugTaken: string;
        workspaceNotFound: string;
        alreadyArchived: string;
        workspaceHasAgents: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
        refused: string;
        lastOwner: string;
        targetNotMember: string;
        roleNotGrantable: string;
        insufficientRole: string;
        githubNotAuthorized: string;
        installationUnreachable: string;
        repositoryNotInstalled: string;
        mainRepoClaimed: string;
        repositoryLinkedElsewhere: string;
        repositoryUnparsable: string;
      };
    };
    invitations: {
      title: string;
      email: string;
      role: string;
      sent: string;
      expires: string;
      never: string;
      empty: string;
    };
    apiKeys: {
      lead: string;
      tableLabel: string;
      columns: {
        name: string;
        prefix: string;
        created: string;
        lastUsed: string;
        expires: string;
        status: string;
        actions: string;
      };
      actions: {
        create: {
          open: string;
          title: string;
          body: string;
          name: string;
          expires: string;
          expiresUtc: string;
          expiresAt: string;
          confirm: string;
          pending: string;
        };
        rotate: {
          open: string;
          title: string;
          body: string;
          confirm: string;
          pending: string;
        };
        revoke: {
          open: string;
          title: string;
          body: string;
          confirm: string;
          pending: string;
        };
        secret: {
          title: string;
          body: string;
          named: string;
        };
        failure: {
          denied: string;
          keyNotFound: string;
          keyExpired: string;
          nameRequired: string;
          expiryNotADay: string;
          expiryInThePast: string;
          refused: string;
          invalid: string;
          pendingApproval: string;
          unavailable: string;
          workspaceArchived: string;
        };
      };
      status: {
        live: string;
        expired: string;
        revoked: string;
      };
      workspace: {
        label: string;
        archived: string;
        archivedNote: string;
      };
      noWorkspace: {
        title: string;
        body: string;
      };
      never: string;
      neverUsed: string;
      empty: string;
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
      };
      filter: {
        label: string;
        active: string;
        all: string;
        allWithCount: string;
      };
      pager: {
        label: string;
        range: string;
        previous: string;
        next: string;
      };
      emptyFiltered: string;
    };
    denied: {
      title: string;
      body: string;
    };
    pending: {
      title: string;
      body: string;
    };
    error: {
      title: string;
      body: string;
    };
    roleCatalog: {
      title: string;
      lead: string;
      enforcement: {
        enforced: string;
        recorded: string;
      };
      tableLabel: string;
      columns: {
        role: string;
        kind: string;
        scope: string;
        permissions: string;
        heldBy: string;
        origin: string;
        actions: string;
      };
      kind: {
        human: string;
        agent: string;
      };
      scope: {
        org: string;
        workspace: string;
      };
      origin: {
        builtIn: string;
        createdBy: string;
        custom: string;
      };
      noPermissions: string;
      empty: string;
      catalog: {
        title: string;
        lead: string;
        covers: string;
      };
    };
    workspaces: {
      title: string;
      tableLabel: string;
      columns: {
        workspace: string;
        role: string;
        status: string;
        actions: string;
      };
      status: {
        live: string;
        archived: string;
      };
      noRole: string;
      empty: string;
    };
    modelFunding: {
      title: string;
      intro: string;
      explain: {
        platform: string;
        byok: string;
      };
      current: {
        title: string;
        none: string;
        provider: string;
        key: string;
        keyEnding: string;
        endpoint: string;
        status: string;
        active: string;
        disabled: string;
        tested: string;
        at: string;
        never: string;
      };
      tiers: {
        balanced: string;
        fast: string;
        precise: string;
      };
      providers: {
        openrouter: {
          name: string;
          hint: string;
        };
        gateway: {
          name: string;
          hint: string;
        };
        openai: {
          name: string;
          hint: string;
        };
        anthropic: {
          name: string;
          hint: string;
          caching: string;
        };
        openai_compatible: {
          name: string;
          hint: string;
        };
      };
      form: {
        title: string;
        replaceTitle: string;
        provider: string;
        key: string;
        show: string;
        hide: string;
        baseUrl: string;
        baseUrlHint: string;
        baseUrlPlaceholder: string;
        models: string;
        balancedHint: string;
        unmappedNote: string;
        test: string;
        testing: string;
        save: string;
        saving: string;
        saved: string;
      };
      verdict: {
        ok: string;
        okWithTools: string;
        refused: string;
        noTools: string;
        noReason: string;
      };
      remove: {
        label: string;
        confirm: string;
        yes: string;
        pending: string;
        cancel: string;
      };
      denied: {
        title: string;
        body: string;
      };
      failure: {
        denied: string;
        keyRequired: string;
        baseUrlRequired: string;
        balancedRequired: string;
        invalid: string;
        refused: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
  };
  run: {
    eyebrow: string;
    notRecorded: string;
    basisNotRecorded: string;
    noSummary: string;
    witnessed: string;
    source: {
      ledger: string;
      tacho: string;
    };
    figures: {
      cost: string;
      turns: string;
      steps: string;
      frames: string;
      started: string;
      sealed: string;
    };
    facts: {
      operator: string;
      model: string;
      machine: string;
      noMachineOnLedger: string;
      operatorKind: {
        human: string;
        agent: string;
        service: string;
      };
    };
    tabs: {
      label: string;
      transcript: string;
      frames: string;
      cost: string;
      chain: string;
      approvals: string;
    };
    transcript: {
      title: string;
      zoomLabel: string;
      zoom: {
        turns: string;
        steps: string;
        everything: string;
      };
      digestOnly: string;
      noBody: string;
      truncated: string;
      openFrame: string;
      empty: string;
      complete: string;
      cut: string;
      runStart: string;
      turn: string;
      turnDone: string;
      turnRunning: string;
      you: string;
      agent: string;
      stepCount: string;
      frameCount: string;
      seqSpan: string;
      ms: string;
      live: string;
      goLive: string;
      recorded: {
        sealed: string;
        halted: string;
      };
      back: string;
      play: string;
      pause: string;
      forward: string;
      scrub: string;
      position: string;
      of: string;
      speedLabel: string;
      speed: string;
      transportNote: string;
      transportNoteGraded: string;
      frameHead: string;
      fidelity: {
        full: string;
        digest_only: string;
      };
      envelope: string;
      recording: string;
      chipsLabel: string;
      chip: {
        prompt: string;
        responses: string;
        tools: string;
        policy: string;
        recall: string;
        usage: string;
        errors: string;
      };
      chipsClear: string;
      emptyFiltered: string;
      more: string;
      readingMore: string;
      loadedMore: string;
      badCursor: string;
      pageFailed: string;
      followLost: string;
      followSealed: string;
      request: string;
      response: string;
      decision: string;
      calledWith: string;
      noHalves: string;
    };
    frames: {
      title: string;
      onThisPage: string;
      columns: {
        seq: string;
        type: string;
        observed: string;
        body: string;
        cost: string;
      };
      stage: string;
      fidelity: {
        full: string;
        digest_only: string;
      };
      noContent: string;
      redacted: string;
      openBody: string;
      pager: string;
      first: string;
      next: string;
      empty: string;
      emptyPage: string;
      body: {
        title: string;
        close: string;
        digest: string;
        contentType: string;
        size: string;
        bytes: string;
        noBytes: string;
        digestOnly: string;
        notText: string;
      };
    };
    cost: {
      title: string;
      notRolledUp: string;
      total: string;
      basisNotRecorded: string;
      cacheHitRate: string;
      turns: string;
      steps: string;
      modelCalls: string;
      toolCalls: string;
      retries: string;
      productiveRatio: string;
      rolledUpAt: string;
      priceEntries: string;
      tokensTitle: string;
      tokens: {
        inputUncached: string;
        cacheRead: string;
        cacheWrite5m: string;
        cacheWrite1h: string;
        output: string;
        reasoning: string;
      };
      byModel: string;
      byTool: string;
      noModelCalls: string;
      noToolCalls: string;
      columns: {
        model: string;
        tool: string;
        calls: string;
        cost: string;
        tokens: string;
      };
    };
    commands: {
      reasonLabel: string;
      reasonHelp: string;
      steerLabel: string;
      steerHelp: string;
      noRecipient: string;
      reread: string;
      ledgerReason: string;
      roleReason: string;
      pause: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
      };
      resume: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
      };
      steer: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
      };
      cancel: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        runNotFound: string;
        noConnectionPoint: string;
        runSealed: string;
        observeTier: string;
        runNotSealed: string;
        digestOnly: string;
        steerText: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
        forkRequiresLedger: string;
        gradeBelowFork: string;
        seqPastSeal: string;
        gapBeforeSeq: string;
        fromSeq: string;
        runB: string;
      };
      observeReason: string;
    };
    record: {
      reread: string;
      summarize: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
        needsRole: string;
        needsBodies: string;
      };
      resummarize: {
        open: string;
      };
      export: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        queued: string;
        needsRole: string;
      };
    };
    gaps: string;
    gap: {
      digest_only: string;
      body_missing: string;
      tool_bodies: string;
      model_calls: string;
      hooks_partial: string;
      unobserved_tail: string;
      chain_break: string;
      telemetry_gap: string;
    };
    tier: {
      gateway: string;
      harness: string;
      observe: string;
    };
    chain: {
      title: string;
      hashRule: string;
      frameCount: string;
      range: string;
      merkleRoot: string;
      tierLabel: string;
      gradeLabel: string;
      gapsTitle: string;
      prefix: string;
      noGaps: string;
      missingFrames: string;
      missingBodies: string;
      missingSequences: string;
      recordedGaps: string;
      sealTitle: string;
      attemptLabel: string;
      sealedAt: string;
      terminalStatus: string;
      sealedFrames: string;
      finalSeq: string;
      finalDigest: string;
      streamDigest: string;
      archive: string;
      unsealed: string;
      checkpointsTitle: string;
      noCheckpoints: string;
      ladderTitle: string;
      ladderWhy: string;
      ladderNoGrade: string;
      rungMet: string;
      rungUnmet: string;
      columns: {
        seq: string;
        head: string;
        frames: string;
        signed: string;
        countersigned: string;
        anchor: string;
      };
      tier: {
        gateway: string;
        harness: string;
        observe: string;
      };
      grade: {
        inspect: string;
        view: string;
        fork: string;
        retry: string;
      };
      gap: {
        digest_only: string;
        body_missing: string;
        tool_bodies: string;
        model_calls: string;
        hooks_partial: string;
        unobserved_tail: string;
        chain_break: string;
        telemetry_gap: string;
      };
    };
    waterfall: {
      title: string;
      total: string;
      basisNotRecorded: string;
      running: string;
      steps: string;
      step: string;
      noCost: string;
      empty: string;
      unpriced: string;
      cut: string;
    };
    replay: {
      forkNeedsLedger: string;
      forkNoGrade: string;
      forkNeedsGrade: string;
      fork: {
        open: string;
        title: string;
        body: string;
        seqLabel: string;
        seqHelp: string;
        confirm: string;
        pending: string;
        minted: string;
      };
      bisect: {
        open: string;
        title: string;
        body: string;
        otherLabel: string;
        otherHelp: string;
        confirm: string;
        pending: string;
        same: string;
        diverged: string;
        keyA: string;
        keyB: string;
        noFrame: string;
      };
    };
    loading: string;
  };
  shell: {
    skipToContent: string;
    loading: string;
    sidebar: {
      label: string;
      navLabel: string;
      sections: {
        workspace: string;
        organization: string;
      };
    };
    nav: {
      fleet: string;
      agents: string;
      tools: string;
      skills: string;
      steering: string;
      spend: string;
      organization: string;
      billing: string;
      audit: string;
      roles: string;
      apiKeys: string;
      modelFunding: string;
    };
    switcher: {
      org: string;
      ws: string;
      current: string;
      denied: string;
      unavailable: string;
    };
    topbar: {
      label: string;
      menu: string;
      breadcrumbs: string;
      search: string;
      searchShortcut: string;
      userMenu: string;
    };
    userMenu: {
      profile: string;
      preferences: string;
      security: string;
      privacy: string;
      switchTheme: string;
      themeNow: string;
      signOut: string;
      signingOut: string;
      signOutFailed: string;
    };
    commands: {
      title: string;
      input: string;
      empty: string;
      footer: {
        move: string;
        open: string;
        escape: string;
        close: string;
      };
    };
    mobileNav: {
      label: string;
      slots: {
        fleet: string;
        agents: string;
        tools: string;
        spend: string;
      };
      more: string;
      waiting: string;
    };
    drawer: {
      title: string;
      close: string;
    };
    account: {
      title: string;
      tabs: {
        profile: string;
        preferences: string;
        security: string;
        privacy: string;
      };
      save: string;
      saving: string;
      saved: string;
      displayName: string;
      email: string;
      emailHint: string;
      verified: string;
      unverified: string;
      editAvatar: string;
      roles: string;
      principal: string;
      rolesHint: string;
      invalid: string;
      denied: string;
      failed: string;
      preferences: {
        loading: string;
        denied: string;
        failed: string;
        locale: string;
        localeName: string;
        localeHint: string;
        timezone: string;
        timezoneHint: string;
        theme: string;
        themes: {
          system: string;
          dark: string;
          light: string;
        };
        preview: string;
        previewDate: string;
        previewNumber: string;
        previewMoney: string;
        save: string;
        saving: string;
        saved: string;
        invalid: string;
      };
      security: {
        signIn: string;
        email: string;
        verified: string;
        unverified: string;
        twoFactor: string;
        twoFactorOn: string;
        twoFactorOff: string;
        authenticator: string;
        authenticatorOn: string;
        authenticatorOff: string;
        setUp: string;
        regenerate: string;
        password: string;
        issue: string;
        issuing: string;
        cancel: string;
        codesRefused: string;
        codesUncertain: string;
        codesIssued: string;
        codesSaved: string;
        codesHeld: string;
        sessions: string;
        sessionsLoading: string;
        sessionsFailed: string;
        thisDevice: string;
        unknownDevice: string;
        unknownAddress: string;
        now: string;
        revoke: string;
        revoking: string;
        revoked: string;
        sessionsHint: string;
        codesBlockedByOther: string;
        codesBlockedElsewhere: string;
      };
      privacy: {
        export: string;
        exportHint: string;
        exportMine: string;
        exportOrg: string;
        exporting: string;
        queued: string;
        ready: string;
        download: string;
        expired: string;
        denied: string;
        deniedOrg: string;
        failed: string;
        erasure: string;
        erasureHint: string;
      };
      orgRole: string;
    };
    assistant: {
      label: string;
      launcher: string;
      launcherHint: string;
      close: string;
      thinking: string;
      recordedAs: string;
      parked: string;
      needsWorkspace: string;
      intro: {
        title: string;
        body: string;
      };
      composer: {
        label: string;
        placeholder: string;
        send: string;
      };
      refused: {
        denied: string;
        invalid: string;
        exhausted: string;
        parked: string;
        unavailable: string;
      };
    };
    avatar: {
      title: string;
      cancel: string;
      save: string;
      saving: string;
      kind: string;
      kinds: {
        icon: string;
        initials: string;
        photo: string;
      };
      icon: string;
      iconHint: string;
      letters: string;
      lettersHint: string;
      typeface: string;
      fonts: {
        sans: string;
        serif: string;
        mono: string;
      };
      photo: string;
      photoHint: string;
      tone: string;
      tones: {
        solid: string;
        soft: string;
        line: string;
      };
      toneHint: string;
      describeIcon: string;
      describeInitials: string;
      describePhoto: string;
      describePhotoNone: string;
      note: string;
      noPhoto: string;
      noLetters: string;
      invalid: string;
      denied: string;
      failed: string;
      photoPlaceholder: string;
    };
  };
  skills: {
    eyebrow: string;
    lede: string;
    loading: string;
    inventory: {
      title: string;
      window: string;
      reported: string;
      noneReported: string;
      notReported: string;
      list: string;
      next: string;
    };
    row: {
      sessions: string;
      lastSeen: string;
      harnesses: string;
    };
    empty: {
      title: string;
      hint: string;
    };
    failure: {
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
      };
      retry: string;
      back: string;
    };
  };
  spend: {
    period: string;
    notRecorded: string;
    basisNotRecorded: string;
    basis: {
      gateway_observed: string;
      client_attested: string;
      mixed: string;
      estimated: string;
    };
    tabs: {
      label: string;
      findings: string;
      operator: string;
      agent: string;
      tool: string;
      waste: string;
      budgets: string;
      pricing: string;
    };
    actions: {
      exportReport: string;
      setBudget: string;
    };
    findings: {
      eyebrow: string;
      heroTitle: string;
      saving: string;
      savingNote: string;
      share: string;
      shareNote: string;
      annualised: string;
      annualisedNote: string;
      spend: string;
      spendNote: string;
      strip: {
        label: string;
        tail: string;
      };
      facts: string;
      note: string;
      list: string;
      emptyTitle: string;
      empty: string;
      rank: string;
      kind: {
        cache_writes_never_read: string;
        duplicate_tool_calls: string;
        repeated_shell_commands: string;
        unpaged_results: string;
      };
      level: {
        tool: string;
        agent: string;
        operator: string;
        workspace: string;
      };
      confidence: {
        high: string;
        medium: string;
      };
      why: string;
      fixLabel: string;
      cites: string;
      shareOfIdentified: string;
      shareUnknown: string;
      evidence: {
        open: string;
        eyebrow: string;
        back: string;
        atStake: string;
        atStakeNote: string;
        confidence: string;
        covered: string;
        coveredValue: string;
        coveredNote: string;
        tokens: string;
        tokensValue: string;
        tokensNote: string;
        measured: string;
        counterfactual: string;
        runs: string;
        runsEmpty: string;
        columns: {
          run: string;
          startedAt: string;
          measured: string;
          counterfactual: string;
        };
        note: string;
      };
      fix: {
        open: string;
        title: string;
        body: string;
        record: string;
        recording: string;
        dismiss: string;
        dismissing: string;
        dismissNote: string;
        failure: {
          orgRoleRequired: string;
          noPrincipal: string;
          notOpen: string;
          notFound: string;
          pendingApproval: string;
          invalid: string;
          refused: string;
          unavailable: string;
        };
      };
    };
    strip: {
      spend: string;
      proven: string;
      provenNote: string;
      accepted: string;
      acceptedNote: string;
      productiveRatio: string;
      productiveRatioNote: string;
    };
    columns: {
      provider: string;
      runs: string;
      calls: string;
      spend: string;
      proven: string;
      productiveRatio: string;
    };
    groups: {
      operator: {
        title: string;
        key: string;
        empty: string;
      };
      agent: {
        title: string;
        key: string;
        empty: string;
      };
      model: {
        title: string;
        key: string;
        empty: string;
      };
      tool: {
        title: string;
        key: string;
        empty: string;
      };
    };
    waste: {
      wasted: string;
      share: string;
      runsWithWaste: string;
      largestCause: string;
      noCause: string;
      byCause: string;
      none: string;
      proof: string;
      cause: {
        cache_write_never_read: string;
      };
    };
    budgets: {
      title: string;
      empty: string;
      scopeColumn: string;
      periodColumn: string;
      limitColumn: string;
      spentColumn: string;
      positionColumn: string;
      scope: {
        org: string;
        workspace: string;
      };
      monthly: string;
      rolling: string;
      noLimit: string;
      disabled: string;
      position: string;
      state: {
        ok: string;
        threshold_50: string;
        threshold_80: string;
        threshold_95: string;
        exceeded: string;
      };
    };
    pricing: {
      class: {
        input_uncached: string;
        cache_read: string;
        cache_write_5m: string;
        cache_write_1h: string;
        output: string;
        reasoning: string;
        server_tool_request: string;
        embedding_input: string;
        rerank: string;
        image: string;
        video_second: string;
      };
      per: {
        token: string;
        request: string;
        image: string;
        second: string;
      };
      source: {
        list: string;
        negotiated: string;
        override: string;
      };
      unpriced: {
        title: string;
        note: string;
        none: string;
        columns: {
          model: string;
          provider: string;
          calls: string;
          tokens: string;
          missing: string;
          recordedAs: string;
          action: string;
        };
        noProvider: string;
        noCost: string;
        estimated: string;
        setRate: string;
      };
      book: {
        title: string;
        note: string;
        empty: string;
        columns: {
          model: string;
          provider: string;
          tokenClass: string;
          rate: string;
          region: string;
          source: string;
          effective: string;
          action: string;
        };
        open: string;
        until: string;
        anyRegion: string;
        platformPriced: string;
      };
      dialog: {
        open: string;
        title: string;
        body: string;
        provider: string;
        model: string;
        aliases: string;
        aliasesHint: string;
        effectiveFrom: string;
        effectiveFromHint: string;
        rates: string;
        ratesHint: string;
        showAllClasses: string;
        submit: string;
        pending: string;
        errors: {
          providerInvalid: string;
          modelInvalid: string;
          regionInvalid: string;
          aliasesInvalid: string;
          effectiveFromInvalid: string;
          tokenClassInvalid: string;
          rateInvalid: string;
          ratesEmpty: string;
        };
        partial: {
          written: string;
          noneWritten: string;
          notWritten: string;
        };
      };
      remove: {
        open: string;
        label: string;
        title: string;
        body: string;
        kept: string;
        submit: string;
        pending: string;
        unpricedTitle: string;
        unpriced: string;
        unpricedClose: string;
        confirmUnpricedTitle: string;
        confirmUnpriced: string;
        confirmUnpricedSubmit: string;
        confirmUnpricedCancel: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
    drill: {
      title: {
        operator: string;
        agent: string;
        tool: string;
      };
      back: string;
      perCall: string;
      perRun: string;
      share: string;
      byDay: string;
      day: string;
      tools: string;
      toolsEmpty: string;
    };
    failure: {
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
      };
    };
    empty: {
      title: string;
      body: string;
      back: string;
    };
    budgetDialog: {
      title: string;
      scope: string;
      period: string;
      rolling: string;
      windowDays: string;
      limit: string;
      limitHint: string;
      enabled: string;
      submit: string;
      pending: string;
      errors: {
        limitInvalid: string;
        windowDaysInvalid: string;
      };
      alert: {
        denied: string;
        failed: string;
      };
    };
    exportDialog: {
      title: string;
      month: string;
      monthHint: string;
      submit: string;
      pending: string;
      errors: {
        monthInvalid: string;
      };
      alert: {
        denied: string;
        failed: string;
      };
    };
    fleet: {
      label: string;
      spendToday: string;
      spendTodayNote: string;
      cacheHitRate: string;
      cacheHitRateNote: string;
    };
  };
  steering: {
    tabs: {
      label: string;
      records: string;
      proposals: string;
      prs: string;
    };
    failure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
    pager: {
      label: string;
      range: string;
      previous: string;
      next: string;
    };
    freshness: {
      title: string;
      lead: string;
      version: string;
      repository: string;
      published: string;
      unbound: string;
      gatesLegend: string;
      autoSync: string;
      autoSyncHint: string;
      blockStaleRuns: string;
      blockStaleRunsHint: string;
    };
    status: {
      proposed: string;
      pr_open: string;
      checks_running: string;
      checks_passed: string;
      checks_failed: string;
      merged: string;
      rejected: string;
    };
    records: {
      title: string;
      lead: string;
      filter: string;
      all: string;
      emptyTitle: string;
      empty: string;
      emptyKind: string;
      authority: string;
      facts: {
        version: string;
        commit: string;
        path: string;
        published: string;
      };
    };
    proposals: {
      title: string;
      lead: string;
      emptyTitle: string;
      empty: string;
      checks: string;
      source: string;
      support: string;
      runs: string;
      agents: string;
      records: string;
      evidence: string;
      none: string;
      viewPr: string;
    };
    prs: {
      title: string;
      lead: string;
      empty: string;
      number: string;
      columns: {
        pr: string;
        branch: string;
        kind: string;
        state: string;
      };
    };
    pr: {
      heading: string;
      title: string;
      machine: string;
      goToPr: string;
      rejected: string;
      notOpened: string;
      modeUnread: string;
      modes: {
        solo: string;
        team: string;
        regulated: string;
      };
      facts: {
        repository: string;
        branch: string;
        branchInto: string;
        head: string;
        headUnknown: string;
        path: string;
        governance: string;
      };
      checks: {
        title: string;
        names: {
          schema: string;
          lineage_uniqueness: string;
          record_hash: string;
          secret_pii_scan: string;
          conflict_against_active: string;
          constraint_effect: string;
        };
        statuses: {
          pending: string;
          running: string;
          passed: string;
          failed: string;
        };
      };
      body: string;
      onMerge: {
        title: string;
        publishes: string;
        version: string;
        promotion: string;
        review: string;
      };
      merged: {
        title: string;
        commit: string;
        at: string;
        promotion: string;
        record: string;
      };
    };
    actions: {
      open: {
        open: string;
        title: string;
        rerun: string;
        body: string;
        confirm: string;
        rerunConfirm: string;
        pending: string;
      };
      dismiss: {
        open: string;
        title: string;
        body: string;
        reason: string;
        confirm: string;
        pending: string;
      };
      merge: {
        confirm: string;
        pending: string;
        blocked: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        separationOfDuties: string;
        proposalNotFound: string;
        proposalMoved: string;
        lineagePrOpen: string;
        governanceUnreadable: string;
        repositoryMissing: string;
        checksNotPassed: string;
        headMoved: string;
        baseMoved: string;
        githubRefused: string;
        mergeTimeUnknown: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
  };
  tools: {
    eyebrow: string;
    lede: string;
    loading: string;
    notCarried: string;
    nextPage: string;
    roles: {
      owner: string;
      admin: string;
      member: string;
      billing: string;
      compliance: string;
      viewer: string;
    };
    tabs: {
      label: string;
      registry: string;
      connections: string;
      switches: string;
      mandates: string;
      switchesOn: string;
      switchesOnAtLeast: string;
      autoapprovals: string;
    };
    gate: {
      open: string;
      killed_version: string;
      killed_server: string;
      killed_class: string;
    };
    registry: {
      title: string;
      lead: string;
      categories: string;
      allCategories: string;
      categoriesNote: string;
      allOnPage: string;
      categoriesDeclaredNote: string;
      categoriesFilteredNote: string;
      unclassified: string;
      noTags: string;
      emptyCategory: string;
      gateNote: string;
      empty: {
        title: string;
        body: string;
      };
      columns: {
        version: string;
        category: string;
        hazard: string;
        gate: string;
        egress: string;
        financial: string;
        origin: string;
        digest: string;
        calls: string;
      };
      names: {
        label: string;
        labels: string;
        api: string;
      };
      risk: {
        low: string;
        medium: string;
        high: string;
        critical: string;
      };
      sideEffect: {
        read: string;
        write: string;
        irreversible: string;
      };
      egress: {
        local: string;
        org_tenant: string;
        third_party: string;
      };
      financial: {
        yes: string;
      };
      origin: {
        declared: string;
        imported: string;
      };
    };
    tool: {
      yes: string;
      no: string;
      unclassified: string;
      source: {
        builtin: string;
        custom: string;
        mcp: string;
        foundry: string;
      };
      facts: {
        id: string;
        capability: string;
        source: string;
        gate: string;
        origin: string;
        digest: string;
        readOnly: string;
        enabled: string;
        classifiedAt: string;
        measures: string;
        updatedAt: string;
      };
      classify: {
        lead: string;
        riskGrade: string;
        sideEffect: string;
        egress: string;
        consequenceTags: string;
        tagsHint: string;
        dataClasses: string;
        dataClassesHint: string;
        dataClassesPlaceholder: string;
        reason: string;
        reasonHint: string;
        confirm: string;
        pending: string;
        denied: string;
        tagsPlaceholder: string;
      };
    };
    import: {
      open: string;
      title: string;
      body: string;
      serverId: string;
      tools: string;
      toolsHint: string;
      confirm: string;
      pending: string;
      done: string;
      serverIdPlaceholder: string;
    };
    connections: {
      title: string;
      lead: string;
      noRun: string;
      brokerNote: string;
      notCarriedNote: string;
      empty: {
        title: string;
        body: string;
      };
      columns: {
        grant: string;
        server: string;
        run: string;
        connection: string;
        scope: string;
        ttl: string;
        state: string;
      };
      ttl: string;
      downscope: {
        token_exchange: string;
        session_policy: string;
        restricted_key: string;
        none: string;
      };
      authKind: {
        oauth: string;
        secret: string;
      };
      status: {
        active: string;
        expired: string;
        revoked: string;
      };
    };
    switches: {
      title: string;
      lead: string;
      generation: string;
      classHeading: string;
      scopedHeading: string;
      empty: string;
      truncated: string;
      allowing: string;
      denying: string;
      flippedByUnrecorded: string;
      takesEffect: string;
      kinds: {
        class: string;
        org: string;
        workspace: string;
        tool_server: string;
        tool_version: string;
        connection: string;
        agent: string;
        operator: string;
      };
      blastRadius: {
        class: string;
        org: string;
        workspace: string;
        tool_server: string;
        tool_version: string;
        connection: string;
        agent: string;
        operator: string;
      };
      facts: {
        blastRadius: string;
        takesEffect: string;
        flippedBy: string;
        reason: string;
        clearedAt: string;
      };
      dialog: {
        openHeader: string;
        openDeny: string;
        openAllow: string;
        titleDeny: string;
        titleAllow: string;
        kind: string;
        target: string;
        targetHint: {
          class: string;
          org: string;
          workspace: string;
          tool_server: string;
          tool_version: string;
          connection: string;
          agent: string;
          operator: string;
        };
        blastTitle: string;
        blastBody: string;
        restoreTitle: string;
        restoreBody: string;
        classNote: string;
        connectionNote: string;
        reason: string;
        takesEffect: string;
        takesEffectValue: string;
        takesEffectValueIfChanged: string;
        recordedAs: string;
        recordedAsValue: string;
        confirmDeny: string;
        confirmAllow: string;
        pending: string;
        unchanged: string;
      };
      noNames: string;
    };
    failure: {
      back: string;
      denied: {
        title: string;
        body: string;
        signedIn: string;
        needed: string;
        decidedBy: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
        retry: string;
      };
    };
    actions: {
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        serverNotFound: string;
        versionNotFound: string;
        killSwitchOn: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
        consequenceRoleRequired: string;
        noRoleCoversAllTags: string;
        ruleIdTaken: string;
        ruleNotFound: string;
        noToolMatches: string;
        ruleNotGated: string;
        measureNotDeclared: string;
        measureWrongType: string;
        tooManyConsequences: string;
      };
    };
    mandates: {
      title: string;
      lead: string;
      empty: string;
      emptyDetail: string;
      notGranted: string;
      requestedBy: string;
      columns: {
        mandate: string;
        agent: string;
        grantedBy: string;
        purpose: string;
        perCall: string;
        perPeriod: string;
        settled: string;
        reserved: string;
        remaining: string;
        validTo: string;
        status: string;
        tools: string;
      };
      status: {
        draft: string;
        active: string;
        expired: string;
        revoked: string;
      };
      truncated: string;
      partial: string;
      emptyListed: string;
      emptyListedDetail: string;
    };
    grant: {
      open: string;
      title: string;
      body: string;
      grantRequest: string;
      grantRequestLabel: string;
      titleRequest: string;
      bodyRequest: string;
      moneyNotCarried: string;
      agentOption: string;
      agentsPartial: string;
      agentsUnavailable: string;
      agentsEmpty: string;
      consequenceOther: string;
      consequenceTagsHint: string;
      toolsHint: string;
      limits: string;
      limitsHint: string;
      measureHint: string;
      unitHint: string;
      perPeriodHint: string;
      period: string;
      periods: {
        daily: string;
        weekly: string;
        monthly: string;
      };
      targets: string;
      targetsHint: string;
      approval: string;
      approvalHint: string;
      alwaysHumanForHint: string;
      humanAboveValueHint: string;
      approversHint: string;
      purposeHint: string;
      validToHint: string;
      confirm: string;
      confirmRequest: string;
      pending: string;
      fields: {
        agentId: string;
        consequenceTags: string;
        measure: string;
        unit: string;
        perCall: string;
        perPeriod: string;
        callsPerDay: string;
        tools: string;
        targetMeasure: string;
        targetAllow: string;
        targetDeny: string;
        alwaysHumanFor: string;
        humanAboveMeasure: string;
        humanAboveValue: string;
        approvers: string;
        purpose: string;
        validFrom: string;
        validTo: string;
      };
      failure: {
        orgRoleRequired: string;
        noRoleCoversAllTags: string;
        noPrincipal: string;
        agentNotFound: string;
        agentHasNoPrincipal: string;
        mandateNotFound: string;
        notADraft: string;
        noToolMatches: string;
        measureNotDeclared: string;
        measureUnitMismatch: string;
        timeZoneUnavailable: string;
        timeZoneUnsupported: string;
        refused: string;
        invalidField: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
    autoApprovals: {
      title: string;
      lead: string;
      floors: string;
      counted: string;
      on: string;
      off: string;
      written: string;
      writtenUnattributed: string;
      unstamped: string;
      checkedAgainst: string;
      empty: {
        title: string;
        body: string;
      };
      tiles: {
        label: string;
        on: {
          title: string;
          basis: string;
        };
        released: {
          title: string;
          basis: string;
        };
        held: {
          title: string;
          basis: string;
        };
      };
      columns: {
        rule: string;
        appliesTo: string;
        requires: string;
        released: string;
        held: string;
        on: string;
        actions: string;
      };
      requires: {
        ceiling: string;
        allow: string;
        standing: string;
        hours: string;
        floorsOnly: string;
      };
      days: {
        "1": string;
        "2": string;
        "3": string;
        "4": string;
        "5": string;
        "6": string;
        "7": string;
      };
      editor: {
        openCreate: string;
        openEdit: string;
        titleCreate: string;
        titleEdit: string;
        id: string;
        idHint: string;
        name: string;
        tools: string;
        toolsHint: string;
        maxMeasures: string;
        maxMeasuresHint: string;
        allowTargets: string;
        allowTargetsHint: string;
        standingMinutes: string;
        standingMinutesHint: string;
        hoursOn: string;
        hours: string;
        timezone: string;
        timezoneHint: string;
        start: string;
        end: string;
        enabled: string;
        checks: string;
        confirmCreate: string;
        confirmEdit: string;
        pending: string;
        unreadable: {
          maxMeasures: string;
          allowTargets: string;
        };
      };
      toggle: {
        on: string;
        off: string;
      };
      delete: {
        open: string;
        title: string;
        body: string;
        keep: string;
        switchOff: string;
        confirm: string;
        pending: string;
      };
    };
  };
  ui: {
    brand: {
      name: string;
      home: string;
    };
    dialog: {
      close: string;
    };
    record: {
      kinds: {
        rule: string;
        constraint: string;
        procedure: string;
        fact: string;
        memory: string;
        preference: string;
      };
      unclassified: string;
      force: string;
      effects: {
        require: string;
        forbid: string;
      };
      scope: string;
      scopes: {
        repository: string;
        workspace: string;
      };
      lineage: string;
    };
    runStatus: {
      live: string;
      sealed: string;
      halted: string;
    };
    generated: {
      label: string;
      provenance: string;
    };
    replayGrade: {
      inspect: {
        label: string;
        help: string;
      };
      view: {
        label: string;
        help: string;
      };
      fork: {
        label: string;
        help: string;
      };
      retry: {
        label: string;
        help: string;
      };
    };
    readFailure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
    measure: {
      count: string;
    };
    mandateBar: {
      title: string;
      of: string;
      period: {
        daily: string;
        weekly: string;
        monthly: string;
      };
      settled: string;
      reserved: string;
      remaining: string;
      label: string;
      labelReserved: string;
      overLimit: string;
    };
    mandateScope: {
      everyTool: string;
      noTool: string;
    };
    mandateAuthority: {
      noLimit: string;
      window: string;
      period: {
        daily: string;
        weekly: string;
        monthly: string;
      };
    };
  };
  workspaceSettings: {
    open: string;
    title: string;
    mainRepository: {
      heading: string;
      about: string;
      loading: string;
      connected: string;
      installRefused: string;
      installUnverified: string;
      install: {
        heading: string;
        body: string;
        unreachable: string;
        action: string;
        connect: string;
      };
      unconfigured: string;
      picker: {
        heading: string;
        loading: string;
        filterLabel: string;
        filterPlaceholder: string;
        listLabel: string;
        empty: string;
        noMatch: string;
        private: string;
        defaultBranch: string;
        truncated: string;
        bind: string;
        binding: string;
        none: string;
      };
      bound: {
        heading: string;
        defaultRef: string;
        boundAt: string;
        open: string;
        retired: string;
        reconnect: string;
        reconnecting: string;
        fixed: string;
        refDrift: string;
        reapprove: string;
        reapproving: string;
      };
      manage: string;
      installChoose: string;
      installNone: string;
      installations: {
        heading: string;
        about: string;
        loading: string;
        listLabel: string;
        allRepositories: string;
        selectedRepositories: string;
        attach: string;
        attaching: string;
        none: string;
      };
    };
    repositories: {
      heading: string;
      about: string;
      loading: string;
      listLabel: string;
      none: string;
      onlyMain: string;
      roleMain: string;
      roleLinked: string;
      defaultRef: string;
      boundAt: string;
      open: string;
      retired: string;
      unlink: string;
      unlinkConfirm: string;
      unlinkYes: string;
      unlinkNo: string;
      unlinking: string;
      link: {
        heading: string;
        label: string;
        hint: string;
        placeholder: string;
        unparsable: string;
        submit: string;
        pending: string;
      };
    };
    failure: {
      denied: string;
      githubNotConnected: string;
      repositoryNotInstalled: string;
      mainRepoBound: string;
      invalid: string;
      pendingApproval: string;
      refused: string;
      unavailable: string;
      githubNotAuthorized: string;
      installationUnreachable: string;
      mainRepo: string;
      repositoryAlreadyLinked: string;
      mainRepoClaimed: string;
      mainRepoUnbound: string;
      repositoryLinkedElsewhere: string;
      mainRepoUnlinkRefused: string;
      repositoryNotLinked: string;
    };
  };
};

declare module "next-intl" {
  interface AppConfig {
    Messages: Messages;
  }
}

export {};
